# Generated by Django 4.2.1 on 2023-05-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Register', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
